### ISSUE TITLE
Watchman crawl failed. Retrying once with node crawler.

### ISSUE THREAD

**Issue by alaale123** [luulsolutions/luulclientchat#2]
when ever i run 
`react-native start `
i was getting this error 
![screenshot from 2017-08-09 19-21-35](https://user-images.githubusercontent.com/29515233/29123573-05089dca-7d38-11e7-84db-2af687f1117c.png)

**Comment by maxto024** [comment]
you need to Increase  amount of inotify watchers

[fellow this link ](https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchersl)

**Comment by alaale123** [comment]
Done thanks
